- name: create dashboard file
  ansible.builtin.template:
    src: dashboard.json
    dest: /tmp/dashboard.json

- name: Add grafana dashboard
  community.grafana.grafana_dashboard:
      grafana_url: http://52.90.212.14:3000
      #grafana_api_key: "{{ lookup('amazon.aws.aws_ssm', 'grafana.api_key', region='us-east-1' ) }}"
      grafana_api_key: "glsa_RamySMmYHJrBp3Xh9g535NdCfYhOuV67_615fcc1e"
      state: present
      commit_message: Updated by ansible
      overwrite: yes
      path: /tmp/dashboard.json
