- name: backend setup for expense
  hosts: all
  become: yes
  tasks:
    - name: disable the nodejs
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: enable the nodejs
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: copy backend.service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: adding the user
      ansible.builtin.user:
       name: expense
    - name: delete the old app content
      ansible.builtin.file:
        path: /app
        state: absent
    - name: creating the app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: downlaod and extract the file
      ansible.builtin.unarchive:
       src: https://expense-artifacts.s3.amazonaws.com/backend.zip
       dest: /app
    - name: download the node dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: installing the mysql client
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: creating the schema
      ansible.builtin.shell: mysql -h mysql-dev.osdevops99.online -uroot -pExpenseApp@1 < /app/schema/backend.sql
    - name: start backend service
      ansible.builtin.systemd:
       name: backend
       state: restarted
       enabled: yes
       daemon-reload: yes
