- name: mysql expense project setup
  hosts: all
  become: yes
  tasks:
    - name: disable mysql default version
      ansible.builtin.shell: dnf module disable mysql -y
    - name: copying the mysql.repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    - name: insatlling the mysql
      ansible.builtin.dnf:
       name: mysql-community-server
       state: present

    - name: starting the mysql service
      ansible.builtin.systemd:
       name: mysqld
       state: restarted
       enabled: yes
    - name: set mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}
