- name: disable the default nodejs
  ansible.builtin.shell: dnf module disable nodejs -y
- name: enable the nodejs
  ansible.builtin.shell: dnf module enable nodejs:18 -y
- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present
- name: copy backend.service
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service
- name: adding the user
  ansible.builtin.user:
    name: expense

- name: import common role - App pre-requisites
  ansible.builtin.import_role:
   name: common
   tasks_from: app-prereq
  vars:
    app_dir: /app
    component: backend

- name: download the node dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app
- name: installing the mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present
- name: creating the schema
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_HOST', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_USER', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_PASS', region='us-east-1' ) }} < /app/schema/backend.sql
- name: start backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes
