groups:
  - name: node_exporter
    rules:
      - alert: instancedown
        expr: up < 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: instance down alert